package API;

public enum Times {
	FORTALEZA, FLAMENGO, VASCO, PALMEIRAS, CURITIBA, BARCELONA, REALMADRID, JUVENTUS, BOTAFOGO, MILAN, AJAX, MUNIQUE,
	ARSENAL, LIVERPOOL, SANTOS, SAOPAULO, MANCHESTER, BENFICA, ATLETICO, CEARA, NAPOLI, BRASIL, RIVERPLATE, NACIONAL,
	INDEPENDIENTE, FERROVIARIO, GUARANI, AMERICA, BAHIA, GOIAS;

	public static Times getRandom() {
		return values()[(int) (Math.random() * values().length)];
	}
}
